services:
  webserver:
    image: caddy:latest
    container_name: byoc-webserver
    ports:
      - 8088:8088
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./webapp/dist:/var/www/html/app
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: byoc-worker
    volumes:
      - ./data/models:/models
      - ./server/server.py:/app/server/server.py
    runtime: nvidia
    ports:
      - 9876:9876
    environment:
#      - "MODEL_ID=Efficient-Large-Model/Sana_Sprint_1.6B_1024px_diffusers"
      - "MODEL_ID=Efficient-Large-Model/Sana_Sprint_0.6B_1024px_diffusers"
      - "ORCH_URL=https://orchestrator:9995"
      - "ORCH_SECRET=orch-secret"
      - "CAPABILITY_NAME=gen-image"
      - "CAPABILITY_DESCRIPTION=generate image from text"
      - "CAPABILITY_URL=http://worker:9876"
      - "CAPABILITY_PRICE_PER_UNIT=100"
      - "CAPABILITY_PRICE_SCALING=1"
      - "CAPABILITY_CAPACITY=2"
      - "PYTHONUNBUFFERED=1"
      - "TORCH_DTYPE=BFLOAT16"
      - "TORCH_COMPILE_TRANSFORMER=true"
      - "QUANTIZE_MODEL=true"
  gateway:
    image: adastravideo/go-livepeer:dynamic-capabilities-3
    container_name: byoc-gateway
    volumes:
      - ./data/gateway:/data
    ports:
      - 9999:9999
    command: ["-gateway",
          "-orchAddr=https://orchestrator:9995",
          "-httpAddr=gateway:9999",
          "-httpIngest=true",
          "-v=6",
          "-network=arbitrum-one-mainnet",
          "-ethUrl=https://arb1.arbitrum.io/rpc",
          "-ethPassword=testbroadcaster",
          "-dataDir=/data"]
  orchestrator:
    image: adastravideo/go-livepeer:dynamic-capabilities-3
    container_name: byoc-orchestrator
    volumes:
      - ./data/orchestrator:/data
    ports:
      - 9995:9995
    command: ["-orchestrator",
          "-orchSecret=orch-secret",
          "-serviceAddr=orchestrator:9995",
          "-v=6",
          "-network=arbitrum-one-mainnet",
          "-ethUrl=https://arb1.arbitrum.io/rpc",
          "-ethPassword=some-random-password",
          "-dataDir=/data",
          "-ethOrchAddr=0x3b28a7d785356dc67c7970666747e042305bfb79",
          "-pricePerUnit=1"]
networks:
  default:
    name: byoc
    external: true