services:
  # Signaling Server - WebRTC signaling and web interface
  unreal-signaling:
    build:
      context: .
      dockerfile: docker/pixel-streaming/signaling/Dockerfile
    image: ghcr.io/its-define/unreal_vtuber/embody-signaling:latest
    container_name: vtuber-unreal-signaling
    restart: unless-stopped
    ports:
      - "8080:8080"     # HTTP web interface
      - "8888:8888"     # Streamer port
      - "8889:8889"     # SFU port
    environment:
      - PUBLIC_IP=${PUBLIC_IP:-auto}
      - HTTP_PORT=8080
      - STREAMER_PORT=8888
      - SFU_PORT=8889
      - STUN_SERVER=${STUN_SERVER:-stun.l.google.com:19302}
      - ENABLE_REST_API=${ENABLE_REST_API:-0}
      - SIGNALING_EXTRA_ARGS=${SIGNALING_EXTRA_ARGS:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - byoc-vtuber-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Embody Game - Headless Unreal Engine with Pixel Streaming
  unreal-game:
    image: ghcr.io/its-define/unreal_vtuber/embody-ue-ps:latest
    container_name: vtuber-unreal-game
    restart: unless-stopped
    runtime: nvidia
    ulimits:
      nofile:
        soft: ${HOST_ULIMIT_NOFILE:-1040}
        hard: ${HOST_ULIMIT_NOFILE:-1040}
    ports:
      - "7777:7777"
      - "9877:9877"
    depends_on:
      unreal-signaling:
        condition: service_healthy
    environment:
      - PIXEL_STREAMING_URL=ws://unreal-signaling:8888
      - HOST_ULIMIT_NOFILE=1040
      - ULIMIT_NOFILE=1040
      - HOST_LIB_PATHS=/host-libs/usr/lib/x86_64-linux-gnu:/host-libs/lib/x86_64-linux-gnu:/host-libs/lib64:/host-libs/usr/lib64:/host-libs/usr/lib/nvidia
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
    volumes:
      - /usr/lib/x86_64-linux-gnu:/host-libs/usr/lib/x86_64-linux-gnu:ro
      - /lib/x86_64-linux-gnu:/host-libs/lib/x86_64-linux-gnu:ro
      - /lib64:/host-libs/lib64:ro
      - /usr/lib64:/host-libs/usr/lib64:ro
      - /usr/lib/nvidia:/host-libs/usr/lib/nvidia:ro
      - /usr/share/vulkan:/host-libs/usr/share/vulkan:ro
      - /etc/vulkan:/host-libs/etc/vulkan:ro
      - /usr/share/glvnd:/host-libs/usr/share/glvnd:ro
      - ${VTUBER_SESSION_DIR:-/home/ubuntu/vtuber_sessions}:/opt/embody/sessions
    networks:
      - byoc-vtuber-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]