services:
  webserver:
    image: caddy:latest
    container_name: byoc-webserver
    ports:
      - 8088:8088
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./webapp/dist:/var/www/html/app
  worker:
    container_name: byoc-worker
    build:
      dockerfile: Dockerfile.worker
      context: .
    volumes:
      - ./data/outputs:/outputs
      - ./data/checkpoints:/checkpoints
      - ./server.py:/app/server.py
    runtime: nvidia
    ports:
      - 9876:9876
    environment:
      - "ORCH_URL=https://orchestrator:9995"
      - "ORCH_SECRET=orch-secret"
      - "CAPABILITY_NAME=voice-clone"
      - "CAPABILITY_DESCRIPTION=clone your voice"
      - "CAPABILITY_URL=http://worker:9876"
      - "CAPABILITY_PRICE_PER_UNIT=1"
      - "CAPABILITY_PRICE_SCALING=1"
      - "CAPABILITY_CAPACITY=2"
  orchestrator:
    image: adastravideo/go-livepeer:dynamic-capabilities-2
    container_name: byoc-orchestrator
    volumes:
      - ./data/orchestrator:/data
    ports:
      - 9995:9995
    command: ["-orchestrator",
          "-orchSecret=orch-secret",
          "-serviceAddr=0.0.0.0:9995",
          "-v=6",
          "-network=arbitrum-one-mainnet",
          "-ethUrl=https://arb1.arbitrum.io/rpc",
          "-ethPassword=<your-eth-password>",
          "-dataDir=/data",
          "-ethOrchAddr=<your-eth-orch-addr>",
          "-pricePerUnit=1"]
networks:
  default:
    name: byoc
    external: true
