FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN pip install --no-cache-dir requests
RUN pip install huggingface_hub[cli,hf_transfer]

RUN mkdir /models

ENV HUGGINGFACE_HUB_CACHE=/models
ENV DIFFUSERS_CACHE=/models
ENV MODEL_DIR=/models

WORKDIR /app

COPY register_worker.py /app

COPY register_worker.py /app

CMD ["python", "-u", "register_worker.py"]
